# Generated by Django 5.2.8 on 2025-11-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0002_customer_farmer'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
