# Generated by Django 5.2.8 on 2025-11-17 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0003_weatherdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('temperature', models.FloatField()),
                ('cloudcover', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
