# Generated by Django 5.2.8 on 2025-11-18 09:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0004_weatherprediction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.FloatField()),
                ('stock', models.IntegerField()),
                ('reap_date', models.DateField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.farmer')),
            ],
            options={
                'unique_together': {('farmer', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('stock', models.IntegerField()),
                ('reap_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_items', to='farmer_app.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.product')),
            ],
            options={
                'unique_together': {('farmer', 'product')},
            },
        ),
    ]
