# Generated by Django 5.2.8 on 2025-11-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0006_alter_product_unique_together_product_discount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('farmer', 'name')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
