# Generated by Django 5.2.8 on 2025-11-19 02:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0007_alter_product_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('stock', models.IntegerField()),
                ('discount', models.FloatField(default=0)),
                ('price', models.FloatField()),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.farmer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.product')),
            ],
        ),
        migrations.DeleteModel(
            name='MarketItem',
        ),
    ]
