# Generated by Django 5.2.8 on 2025-11-19 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0008_market_delete_marketitem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
    ]
