# Generated by Django 5.2.8 on 2025-11-21 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0011_remove_cart_customer_id_cart_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('action', models.CharField(choices=[('ADD', 'Add to Cart'), ('REMOVE', 'Remove from Cart'), ('PURCHASE', 'Purchase')], max_length=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_at_action', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_at_action', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_at_action', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.customer')),
            ],
        ),
    ]
