# Generated by Django 5.2.8 on 2025-11-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0013_alter_customeraction_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraction',
            name='action',
            field=models.CharField(choices=[('ADD', 'Add to Cart'), ('REMOVE', 'Remove from Cart'), ('PURCHASE', 'Purchase')], max_length=10),
        ),
    ]
