# Generated by Django 5.2.8 on 2025-11-24 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0014_alter_customeraction_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('purchase_prob', models.FloatField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer_app.customer')),
            ],
            options={
                'ordering': ['-purchase_prob'],
                'unique_together': {('customer', 'crop')},
            },
        ),
    ]
