# Generated by Django 5.2.8 on 2025-11-24 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0015_customerrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerrecommendation',
            name='updated_at',
        ),
    ]
