# Generated by Django 5.2.8 on 2025-11-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0016_remove_customerrecommendation_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='discount_sensitivity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_profiled',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='price_elasticity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='customer',
            name='stock_urgency',
            field=models.FloatField(default=0.0),
        ),
    ]
