# Generated by Django 5.2.8 on 2025-11-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0017_customer_discount_sensitivity_customer_last_profiled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('predicted_yield', models.FloatField()),
                ('synthetic_price', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
