# Generated by Django 5.2.8 on 2025-11-27 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer_app', '0018_cropprices'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCropForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('price_estimate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
